Add `prometheus-push-format` to allow selecting text format
creativeprojects/resticprofile pull request #281
Opened 2023-11-01 20:18 UTC by watsonbox

The default golang client push format [is `FmtProtoDelim`](https://github.com/prometheus/client_golang/blob/f030c3d062e5180830979221733d46d286790bac/prometheus/push/push.go#L112C15-L112C35).

However, some implementations do not support protocol buffers, [including VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3745).

This PR adds the ability to select a simple text format in such cases.

By default (protocol buffers):

![image](https://github.com/creativeprojects/resticprofile/assets/17737/09791475-293a-4249-ad5e-4f682a42d744)

With `prometheus-push-format: text`:

![image](https://github.com/creativeprojects/resticprofile/assets/17737/5b66db38-6871-4505-9e35-aa215c2ebeed)

2023-11-01 20:42 UTC, jkellerer commented
Thanks a lot, wasn’t even aware that it uses protobuf by default. 

Should we make “text” the default format? 

The efficiency gains of the binary protocol shouldn’t be too much in this use case so the default could be a setting that works in all cases.

2023-11-01 20:45 UTC, watsonbox commented
> Should we make “text” the default format?

It did cross my mind, but I figured you'd be less keen on that due to it being a (potentially) breaking change. In reality it seems likely that endpoints accepting protocol buffers will also accept plain text, but I've really no idea.

2023-11-01 20:47 UTC, watsonbox commented
I suppose from a consistency POV it also makes sense that the default format used in this repo matches the default format used by the Prometheus client library.

2023-11-01 20:54 UTC, jkellerer commented
Ok, agree. Thanks a lot!

2023-11-01 21:26 UTC, creativeprojects requested changes
Agree it makes sense to keep the library default.

It looks good to me,
But could we add a little note in the documentation about it?

2023-11-01 21:44 UTC, watsonbox commented
> But could we add a little note in the documentation about it?

Done, although in attempting to do so I actually came across [this Prometheus documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#exposition-formats) which I hadn't seen before. I'm not sure if it changes the reasoning above, but it does make a slightly more compelling case for simply changing this to text.

2023-11-01 21:57 UTC, creativeprojects commented
> NOTE: Some earlier versions of Prometheus supported an exposition format based on [Protocol Buffers](https://developers.google.com/protocol-buffers/) (aka Protobuf) in addition to the current text-based format. As of version 2.0, however, Prometheus no longer supports the Protobuf-based format. You can read about the reasoning behind this change in [this document](https://github.com/OpenObservability/OpenMetrics/blob/main/legacy/markdown/protobuf_vs_text.md). However, beginning with Prometheus v2.40, there is experimental support for native histograms, which – at least in its initial experimental state – utilizes the old Protobuf format (with some newer additions) again. Therefore, a very recent Prometheus server with the experimental native histogram support enabled, will again be able to ingest the Protobuf format. This support is experimental and might get removed again.

I'm tempted to use `text` as default then.

As a breaking change, if any, users would discover very quickly that the metrics are no longer going into their monitoring system, and would easily change it back to `protobuf`.
No data were killed 😆 

Thoughts?

2023-11-02 17:59 UTC, watsonbox commented
Makes sense 👍. I made the update.

2023-11-02 18:56 UTC, creativeprojects commented
Thanks!

@jkellerer are you OK with changing the default to `text`?

2023-11-02 18:56 UTC, creativeprojects approved these changes

2023-11-05 09:52 UTC, jkellerer commented
@creativeprojects , yes `text` is fine, was also my original thought. Since the extra info seems to suggest that protobuf is more a legacy or exceptional format, using `text` is the way to go and prevents that this config has to be adjusted (in most cases) which should always be the goal 😀. 

Still funny that the default client uses it by default which was a valid argument for keeping it but as long a more compatible option is available we should use this (as default).

2023-11-05 10:54 UTC, merged